### ISSUE TITLE
Merge redev with main

### ISSUE THREAD

**Issue by ebrintn** [dekoning-lab/slim-tree#79]
Needed for merge:

- [x] Fix bugs issues #78 and #77
- [x] Update output (iss #80) 
- [x] Update examples
- [x] Update readme (iss #66)
- [x] Merge - Erin to do once rest is complete

**Comment by ebrintn** [comment]
Are we close to being able to do this @afarineshp

**Comment by ebrintn** [comment]
Finish unit tests and examples and then can merge finally

**Comment by ebrintn** [comment]
Unit tests finished and bugs fixed

**Comment by ebrintn** [comment]
@afarineshp I wanted to let you know that I found one more bug in the fitness of genomes that had premature stop codons when I was fixing this - you should know that the software was making all fitnesses effectively 0 regardless of where the stop codon was, instead of cutting everything post stop codon off.

**Comment by ebrintn** [comment]
I believe this is done.
